version: '3.9'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: aura_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: aura_user
      MYSQL_PASSWORD: aura_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    restart: always
    command: daphne -b 0.0.0.0 -p 8000 aura_project.asgi:application
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  mysql_data:
